/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_nemu_free(a: number, b: number): void;
export function nemu_new(a: number, b: number, c: number): void;
export function nemu_next_frame(a: number, b: number): void;
export function nemu_update_controller(a: number, b: number): void;
export function __wbg_controller_free(a: number, b: number): void;
export function __wbg_get_controller_dpad_n(a: number): number;
export function __wbg_set_controller_dpad_n(a: number, b: number): void;
export function __wbg_get_controller_dpad_s(a: number): number;
export function __wbg_set_controller_dpad_s(a: number, b: number): void;
export function __wbg_get_controller_dpad_w(a: number): number;
export function __wbg_set_controller_dpad_w(a: number, b: number): void;
export function __wbg_get_controller_dpad_e(a: number): number;
export function __wbg_set_controller_dpad_e(a: number, b: number): void;
export function __wbg_get_controller_start(a: number): number;
export function __wbg_set_controller_start(a: number, b: number): void;
export function __wbg_get_controller_select(a: number): number;
export function __wbg_set_controller_select(a: number, b: number): void;
export function __wbg_get_controller_a(a: number): number;
export function __wbg_set_controller_a(a: number, b: number): void;
export function __wbg_get_controller_b(a: number): number;
export function __wbg_set_controller_b(a: number, b: number): void;
export function controller_new(): number;
export function set_panic_hook(): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
